version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_reconciliation
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/identity_reconciliation
      PORT: 3000
      NODE_ENV: production
    ports:
      - '3000:3000'
    command: sh -c "npx prisma migrate deploy && npm start"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data: 