services:
  # PostgreSQL Database
  - type: pserv
    name: bitespeed-postgres
    plan: free
    databaseName: bitespeed_identity
    user: bitespeed
    region: oregon

  # Web Service
  - type: web
    name: bitespeed-identity-service
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-postgres
          property: connectionString
      - key: LOG_LEVEL
        value: INFO
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: RATE_LIMIT_IDENTIFY_MAX
        value: 10
      - key: MAX_CONTACTS_PER_OPERATION
        value: 1000
      - key: MAX_CONTACT_CHAIN_DEPTH
        value: 10
      - key: ENABLE_ENHANCED_VALIDATION
        value: true
      - key: ENABLE_BUSINESS_RULES
        value: true
      - key: REQUEST_TIMEOUT_MS
        value: 30000
      - key: CORS_ORIGINS
        value: "https://bitespeed-identity-service.onrender.com"
    healthCheckPath: /health
    autoDeploy: false
    branch: main
